// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xesvkrmojqvujdontulq.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlc3Zrcm1vanF2dWpkb250dWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTE1MjQsImV4cCI6MjA2Njk4NzUyNH0.Fpsux2AcTO-zj9xa2YHQxZlkJVyzMnClUVpmo5aJG-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});